---
apiVersion: v1
kind: Service
metadata:
  name: oe
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: oe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oe
  namespace: desire6g-smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oe
  template:
    metadata:
      labels:
        app: oe
    spec:
      containers:
      - name: oe
        image: harbor.nbfc.io/desire6g/desire6g-oe:DEFAULTTAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: oe-env
