apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: desire6g-smo
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      protocol: TCP
      targetPort: 15672
      name: port1
    - port: 5672
      protocol: TCP
      targetPort: 5672
      name: port2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: desire6g-smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 15672
              name: port1
            - containerPort: 5672
              name: port2
