apiVersion: v1
kind: Service
metadata:
  name: desire6g-service-catalog
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: desire6g-service-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desire6g-service-catalog
  namespace: desire6g-smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desire6g-service-catalog
  template:
    metadata:
      labels:
        app: desire6g-service-catalog
    spec:
      containers:
      - name: desire6g-service-catalog
        image: harbor.nbfc.io/desire6g/desire6g-service-catalog:DEFAULTTAG
        ports:
        - containerPort: 8000
        env:
        - name: GITHUB_ORG
          valueFrom:
            secretKeyRef:
              name: servicecatalog-creds
              key: GITHUB_ORG
        - name: GITHUB_REPO
          valueFrom:
            secretKeyRef:
              name: servicecatalog-creds
              key: GITHUB_REPO
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: servicecatalog-creds
              key: GITHUB_ACCESS_TOKEN