---
apiVersion: v1
kind: Service
metadata:
  name: so
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32008
  selector:
    app: so
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: so
  namespace: desire6g-smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: so
  template:
    metadata:
      labels:
        app: so
    spec:
      containers:
      - name: so
        image: harbor.nbfc.io/desire6g/desire6g-so:DEFAULTTAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: so-env
