---
apiVersion: v1
kind: Service
metadata:
  name: topology
  namespace: desire6g-smo
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32007
  selector:
    app: topology
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
  namespace: desire6g-smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
      - name: topology
        image: harbor.nbfc.io/desire6g/desire6g-topology:DEFAULTTAG
        ports:
        - containerPort: 8000
